### ISSUE TITLE
[SSD/PyTorch] Get HTTP 404 Error when I download the pretrained PyTorch SSD model weights.

### ISSUE THREAD

**Issue by jiashenC** [NVIDIA/DeepLearningExamples#721]
Related to **SSD/Torch** 

**Describe the bug**
I get HTTP 404 Error when I try to download the SSD pretrained model using PyTorch hub API.

**To Reproduce**
Python API
```python
import torch
precision = 'fp32'
ssd_model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd', model_math=precision)
```

Simple wget the model
```bash
wget https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pt
```

**Expected behavior**
HTTP 404 Error

**Comment by alvarobartt** [comment]
Hi @jiashenC I just created a PR that should fix this issue once it gets merged into the torchhub branch! 🤗

**Comment by jiashenC** [comment]
Thanks for you reply and PR. 

Is this https://ngc.nvidia.com/catalog/models/nvidia:ssd_pyt_ckpt_amp the correct place to look for model weights?

Though I use the command from this website, I still get error.

**Comment by alvarobartt** [comment]
Hi again @jiashenC, as you can see that's the NVIDIA URL to the SSD PyTorch model checkpoint but with AMP precision, and the one you are trying to load on the piece of code you provided above is the one with FP32 precision, which is indeed different:

```python
import torch
precision = 'fp32'
ssd_model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd', model_math=precision)
```

Anyway, the `hubconf.py` file does not contain the references for the AMP precision model, which should maybe be a nice feature to have. Again, please feel free to check it on the PR #727 where you can see which URLs were updated and the SSD FP32 precision that was not updated as long as it isn't available on the NVIDIA Catalog.

**Comment by alvarobartt** [comment]
Just a little recap @jiashenC, I did some research on the FP32 math_mode/precision NVIDIA models and this is what I could find so far...

```
TensorFloat-32 (TF32) is the new math mode in NVIDIA A100 GPUs for handling the matrix math also called tensor operations. TF32 running on Tensor Cores in A100 GPUs can provide up to 10x speedups compared to single-precision floating-point math (FP32) on Volta GPUs.

TF32 Tensor Cores can speed up networks using FP32, typically with no loss of accuracy. It is more robust than FP16 for models which require high dynamic range for weights or activations.

For more information, refer to the TensorFloat-32 in the A100 GPU Accelerates AI Training, HPC up to 20x blog post.

TF32 is supported in the NVIDIA Ampere GPU architecture and is enabled by default.
```

More information regarding the NVIDIA FP32 models at https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Detection/SSD#enabling-tf32

Anyway, the PyTorch model NVIDIA SSD FP32 still seems to be missing... just the TensorFlow one is available! 👍🏻

**Comment by jiashenC** [comment]
Ah, I see. That explains why. I only tried the FP32 weights.

**Comment by alvarobartt** [comment]
Try this @jiashenC 👍🏻 

```python
import torch
precision = 'fp16'
ssd_model = torch.hub.load('alvarobartt/DeepLearningExamples:nvidia-urls-fix', 'nvidia_ssd', model_math=precision)
```

**Comment by nv-kkudrynski** [comment]
The issue is fixed. Also, we will soon make an update to benefit from the recently uploaded checkpoints.

**Comment by jiashenC** [comment]
The SSD endpoint still does not work.
